name: Check Linter Errors

on:
  pull_request:
    branches:
      - development
      - hotfix
      - main
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  check-linter-errors:
    name: Check Linter Errors
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [20.x]
        pnpm-version: [8.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Check linter errors
        run: pnpm run lint
